<?php
/**
 * Pato theme setup.
 *
 * Pato is a block theme: the layout lives in templates/*.html, the design
 * system in theme.json (generated by .dev/build_theme.py), and the sections in
 * patterns/*.php. This file carries only what those cannot express — supports
 * flags, asset enqueues, block styles, pattern categories and the guards that
 * keep the theme graceful when a plugin it can use is not installed.
 *
 * @package Pato
 */

defined( 'ABSPATH' ) || exit;

define( 'PATO_VERSION', '1.1.2' );

/**
 * Theme supports.
 *
 * A block theme gets most of this from theme.json; what remains is the set of
 * flags with no theme.json equivalent.
 */
function pato_setup() {
	load_theme_textdomain( 'pato', get_template_directory() . '/languages' );

	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	add_theme_support( 'editor-styles' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'align-wide' );
	add_theme_support( 'wp-block-styles' );
	add_theme_support(
		'custom-logo',
		array(
			'height'      => 64,
			'width'       => 240,
			'flex-height' => true,
			'flex-width'  => true,
		)
	);

	// style.css is loaded into the editor canvas too, so the menu rows and the
	// block style variations look the same there as on the front end.
	add_editor_style( 'style.css' );
}
add_action( 'after_setup_theme', 'pato_setup' );

/**
 * Front-end styles.
 */
function pato_enqueue_styles() {
	wp_enqueue_style( 'pato-style', get_stylesheet_uri(), array(), PATO_VERSION );
}
add_action( 'wp_enqueue_scripts', 'pato_enqueue_styles' );

/**
 * Block style variations.
 *
 * Deliberately registered without a `style_handle`. That option only enqueues
 * the CSS while WordPress is serving separate core block assets, and any
 * plugin can turn that off site-wide — after which every variation still
 * renders its class and silently loses its styling. The CSS lives in
 * style.css, which always loads.
 */
function pato_register_block_styles() {
	$styles = array(
		'core/button'    => array(
			'pato-outline' => __( 'Outline', 'pato' ),
			'pato-ghost'   => __( 'Underlined', 'pato' ),
		),
		'core/heading'   => array(
			'pato-script' => __( 'Script eyebrow', 'pato' ),
			'pato-ruled'  => __( 'Ruled', 'pato' ),
		),
		'core/paragraph' => array(
			'pato-script' => __( 'Script', 'pato' ),
		),
		'core/image'     => array(
			'pato-frame' => __( 'Inset frame', 'pato' ),
			'pato-lift'  => __( 'Lift on hover', 'pato' ),
		),
		'core/separator' => array(
			'pato-diamond' => __( 'Diamond', 'pato' ),
		),
		'core/list'      => array(
			'pato-ticks' => __( 'Ticks', 'pato' ),
		),
	);

	foreach ( $styles as $block => $variations ) {
		foreach ( $variations as $name => $label ) {
			register_block_style(
				$block,
				array(
					'name'  => $name,
					'label' => $label,
				)
			);
		}
	}
}
add_action( 'init', 'pato_register_block_styles' );

/**
 * Pattern categories.
 *
 * Registered on `init` so the strings are translated, and guarded because
 * these are only used by patterns/*.php, which WordPress may register first.
 */
function pato_register_pattern_categories() {
	$categories = array(
		'pato-menu'     => array(
			'label'       => __( 'Pato: menus', 'pato' ),
			'description' => __( 'Food and drink menus with prices.', 'pato' ),
		),
		'pato-sections' => array(
			'label'       => __( 'Pato: sections', 'pato' ),
			'description' => __( 'Full-width sections for building pages.', 'pato' ),
		),
		'pato-pages'    => array(
			'label'       => __( 'Pato: pages', 'pato' ),
			'description' => __( 'Complete page layouts.', 'pato' ),
		),
	);

	foreach ( $categories as $slug => $args ) {
		register_block_pattern_category( $slug, $args );
	}
}
add_action( 'init', 'pato_register_pattern_categories' );

/**
 * Expand shortcodes inside a core/shortcode block.
 *
 * core/shortcode's render callback only runs wpautop(); the actual expansion
 * is done by do_shortcode() on `the_content`, which never runs for a block
 * template. Without this a template renders the literal text of the shortcode.
 * do_shortcode() on already-expanded output is a no-op, so this is safe to
 * apply unconditionally.
 *
 * @param string $content Rendered block content.
 * @return string
 */
function pato_render_shortcode_block( $content ) {
	return do_shortcode( $content );
}
add_filter( 'render_block_core/shortcode', 'pato_render_shortcode_block' );

require get_template_directory() . '/inc/forms.php';
require get_template_directory() . '/inc/reservations.php';
require get_template_directory() . '/inc/front-page-setup.php';
require get_template_directory() . '/inc/starter-sites.php';
require get_template_directory() . '/inc/repair.php';
require get_template_directory() . '/inc/scheme.php';
require get_template_directory() . '/inc/woocommerce.php';
require get_template_directory() . '/inc/updates.php';
